services:
  - type: web
    name: mishga-site
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: MISHGA_SECRET_KEY
        generateValue: true
      - key: MISHGA_ADMIN_PASSWORD
        value: "mishga2026"
      - key: POSTGRES_URL
        fromDatabase:
          name: mishga-db
          property: connectionString

databases:
  - name: mishga-db
    databaseName: mishga
    user: mishga
